buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'com.guardsquare:proguard-gradle:7.3.2'
    }
}

plugins {
    id 'java-library'
    id 'com.github.johnrengelman.shadow' version '7.0.0'
	id("org.panteleyev.jpackageplugin") version "1.5.2"
}

repositories {
    mavenCentral()
    maven { url 'https://jitpack.io' }
    maven { url 'https://oss.sonatype.org/content/repositories/snapshots' }
}

dependencies {
	implementation fileTree(dir: 'libs', include: ['*.jar', '*.zip'])
	implementation(project(':photon')) {
    	exclude group: 'com.sun.mail'
    	exclude group: 'net.dv8tion'
	} /* Add Photon */

	shadow(fileTree(dir: 'libs', include: ['*.jar']))
	shadow(project(':photon'))
}

tasks.withType(JavaCompile).configureEach { it.options.release = 17 }
sourceCompatibility = targetCompatibility = JavaVersion.VERSION_17

version = '1.0.2'
archivesBaseName = 'launcher-unobfuscated'

/* Create basic JAR */
jar {
	duplicatesStrategy 'exclude'
   	manifest { attributes([ "Main-Class": "com.launcher.LauncherEngine" ]) }
}

/* Add required dependencies */
shadowJar {
	archiveClassifier.set('')
   	configurations = [project.configurations.shadow]
   	duplicatesStrategy 'exclude'
}

tasks.register('proguard', proguard.gradle.ProGuardTask) {
    dependsOn shadowJar
    configuration file('obfuscate.pro')
    injars(tasks.named("shadowJar").flatMap { it.archiveFile })
    outjars(layout.buildDirectory.file("libs/hey-minified.jar"))
    libraryjars(configurations.shadow.filter { it.exists() })
}
proguard.shouldRunAfter shadowJar

/* Create a native executable */
tasks.jpackage {
    input  = "$buildDir/libs/${archivesBaseName}-${version}.jar"
    destination = "$buildDir/libs"

    appName = "WayZ Launcher"
	appDescription = "Install our launcher for our servers"
    vendor = ""

    mainJar = tasks.shadowJar.outputs.files.singleFile
    mainClass = "com.launcher.LauncherEngine"
    appVersion = "${version}";
    fileAssociations = [ "assets/nebulae.properties", "assets/nebulae-image.properties", "assets/nebulae-anim.properties" ]

    windows {
		icon = "$projectDir/assets/launcher.ico"
        winConsole = false

        winShortcut = true
        winShortcutPrompt = true
        
        winMenu = true
        winMenuGroup = "Minecraft Launcher"

        winPerUserInstall = true
    }
    mac {
        icon = "$projectDir/assets/launcher.icns"
    }
    linux {
        icon = "$projectDir/assets/launcher.png"
        linuxShortcut = true
    }
}

tasks.build.dependsOn shadowJar