-keep class javax.**
-keep class java.awt.**
-keep class java.util.logging.**
-keep class jdk.**
-keep class javafx.**
-dontwarn net.dv8tion.**
-dontwarn okhttp3.**
-dontwarn okio.**
-dontwarn org.slf4j.**
-dontwarn com.neovisionaries.ws.client.**

-keepclasseswithmembers public class com.launcher.LauncherEngine {
    public static void main(java.lang.String[]);
}

-keep class com.photon.util.ConsoleManager { *; }

-libraryjars 'C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot\jmods\java.base.jmod'
-libraryjars 'C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot\jmods\java.compiler.jmod'
-libraryjars 'C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot\jmods\java.datatransfer.jmod'
-libraryjars 'C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot\jmods\java.desktop.jmod'
-libraryjars 'C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot\jmods\java.instrument.jmod'
-libraryjars 'C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot\jmods\java.logging.jmod'
-libraryjars 'C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot\jmods\java.management.jmod'
-libraryjars 'C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot\jmods\java.management.rmi.jmod'
-libraryjars 'C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot\jmods\java.naming.jmod'
-libraryjars 'C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot\jmods\java.net.http.jmod'
-libraryjars 'C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot\jmods\java.prefs.jmod'
-libraryjars 'C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot\jmods\java.rmi.jmod'
-libraryjars 'C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot\jmods\java.scripting.jmod'
-libraryjars 'C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot\jmods\java.se.jmod'
-libraryjars 'C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot\jmods\java.security.jgss.jmod'
-libraryjars 'C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot\jmods\java.security.sasl.jmod'
-libraryjars 'C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot\jmods\java.smartcardio.jmod'
-libraryjars 'C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot\jmods\java.sql.jmod'
-libraryjars 'C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot\jmods\java.sql.rowset.jmod'
-libraryjars 'C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot\jmods\java.transaction.xa.jmod'
-libraryjars 'C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot\jmods\java.xml.crypto.jmod'
-libraryjars 'C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot\jmods\java.xml.jmod'
-libraryjars 'C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot\jmods\jdk.accessibility.jmod'
-libraryjars 'C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot\jmods\jdk.attach.jmod'
-libraryjars 'C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot\jmods\jdk.charsets.jmod'
-libraryjars 'C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot\jmods\jdk.compiler.jmod'
-libraryjars 'C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot\jmods\jdk.crypto.cryptoki.jmod'
-libraryjars 'C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot\jmods\jdk.crypto.ec.jmod'
-libraryjars 'C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot\jmods\jdk.crypto.mscapi.jmod'
-libraryjars 'C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot\jmods\jdk.dynalink.jmod'
-libraryjars 'C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot\jmods\jdk.editpad.jmod'
-libraryjars 'C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot\jmods\jdk.hotspot.agent.jmod'
-libraryjars 'C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot\jmods\jdk.httpserver.jmod'
-libraryjars 'C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot\jmods\jdk.incubator.foreign.jmod'
-libraryjars 'C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot\jmods\jdk.incubator.vector.jmod'
-libraryjars 'C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot\jmods\jdk.internal.ed.jmod'
-libraryjars 'C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot\jmods\jdk.internal.jvmstat.jmod'
-libraryjars 'C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot\jmods\jdk.internal.le.jmod'
-libraryjars 'C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot\jmods\jdk.internal.opt.jmod'
-libraryjars 'C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot\jmods\jdk.internal.vm.ci.jmod'
-libraryjars 'C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot\jmods\jdk.internal.vm.compiler.jmod'
-libraryjars 'C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot\jmods\jdk.internal.vm.compiler.management.jmod'
-libraryjars 'C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot\jmods\jdk.jartool.jmod'
-libraryjars 'C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot\jmods\jdk.javadoc.jmod'
-libraryjars 'C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot\jmods\jdk.jcmd.jmod'
-libraryjars 'C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot\jmods\jdk.jconsole.jmod'
-libraryjars 'C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot\jmods\jdk.jdeps.jmod'
-libraryjars 'C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot\jmods\jdk.jdi.jmod'
-libraryjars 'C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot\jmods\jdk.jdwp.agent.jmod'
-libraryjars 'C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot\jmods\jdk.jfr.jmod'
-libraryjars 'C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot\jmods\jdk.jlink.jmod'
-libraryjars 'C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot\jmods\jdk.jpackage.jmod'
-libraryjars 'C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot\jmods\jdk.jshell.jmod'
-libraryjars 'C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot\jmods\jdk.jsobject.jmod'
-libraryjars 'C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot\jmods\jdk.jstatd.jmod'
-libraryjars 'C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot\jmods\jdk.localedata.jmod'
-libraryjars 'C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot\jmods\jdk.management.agent.jmod'
-libraryjars 'C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot\jmods\jdk.management.jfr.jmod'
-libraryjars 'C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot\jmods\jdk.management.jmod'
-libraryjars 'C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot\jmods\jdk.naming.dns.jmod'
-libraryjars 'C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot\jmods\jdk.naming.rmi.jmod'
-libraryjars 'C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot\jmods\jdk.net.jmod'
-libraryjars 'C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot\jmods\jdk.nio.mapmode.jmod'
-libraryjars 'C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot\jmods\jdk.random.jmod'
-libraryjars 'C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot\jmods\jdk.sctp.jmod'
-libraryjars 'C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot\jmods\jdk.security.auth.jmod'
-libraryjars 'C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot\jmods\jdk.security.jgss.jmod'
-libraryjars 'C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot\jmods\jdk.unsupported.desktop.jmod'
-libraryjars 'C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot\jmods\jdk.unsupported.jmod'
-libraryjars 'C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot\jmods\jdk.xml.dom.jmod'
-libraryjars 'C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot\jmods\jdk.zipfs.jmod'