buildscript {
    repositories { mavenCentral() }
    dependencies { classpath 'com.guardsquare:proguard-gradle:7.3.2' }
}

plugins {
    id 'java-library'
    id 'com.github.johnrengelman.shadow' version '7.0.0'
}

configurations {
    allImplementation { extendsFrom implementation }
}

repositories {
    mavenCentral()
    maven { url 'https://jitpack.io' }
    maven { url 'https://oss.sonatype.org/content/repositories/snapshots' }
}

dependencies {
	implementation fileTree(dir: '../libs', include: ['*.jar', '*.zip'])
	implementation(project(':photon')) {
    	exclude group: 'com.sun.mail'
    	exclude group: 'net.dv8tion'
    	exclude group: 'ch.qos.logback'
	}
}

tasks.withType(JavaCompile).configureEach { it.options.release = 17 }
tasks.withType(JavaCompile) { options.encoding = 'UTF-8' }
sourceCompatibility = targetCompatibility = JavaVersion.VERSION_17
compileJava.options.encoding = 'UTF-8'

version = '1.0.0'
archivesBaseName = 'launcher'

/* Create basic JAR */
jar {
	duplicatesStrategy 'exclude'
   	manifest { attributes([ "Main-Class": "com.launcher.LauncherEngine" ]) }
}

/* Add required dependencies */
shadowJar {
	archiveClassifier.set('')
   	configurations = [project.configurations.shadow]
   	duplicatesStrategy 'exclude'
}

tasks.register('proguard', proguard.gradle.ProGuardTask) {
    dependsOn jar
    dependsOn shadowJar
    configuration file('../obfuscate.pro')
    injars(tasks.named("shadowJar").flatMap { it.archiveFile })
    outjars(layout.buildDirectory.file("libs/${archivesBaseName}.jar"))
    libraryjars(configurations.shadow.filter { it.exists() })
    libraryjars(configurations.allImplementation.filter { it.exists() })
}
proguard.shouldRunAfter shadowJar

/* Main build task */
tasks.build.dependsOn proguard