buildscript {
    repositories { mavenCentral() }
}

plugins {
    id 'java-library'
    id 'com.github.johnrengelman.shadow' version '7.0.0'
}

configurations {
    allImplementation { extendsFrom implementation }
}

repositories {
    mavenCentral()
    maven { url 'https://jitpack.io' }
    maven { url 'https://oss.sonatype.org/content/repositories/snapshots' }
}

dependencies {
	implementation fileTree(dir: '../libs', include: ['*.jar', '*.zip'])
    implementation 'com.github.Dansoftowner:FXTaskbarProgressBar:v11.4' // See more here : https://github.com/Dansoftowner/FXTaskbarProgressBar

	/* Apache */
    api 'commons-codec:commons-codec:1.15'
	api 'commons-io:commons-io:2.11.0'

	/* Shadowing */
	shadow fileTree(dir: '../libs', include: ['*.jar', '*.zip'])
    shadow 'com.github.Dansoftowner:FXTaskbarProgressBar:v11.4' // See more here : https://github.com/Dansoftowner/FXTaskbarProgressBar
	shadow 'commons-codec:commons-codec:1.15'
	shadow 'commons-io:commons-io:2.11.0'
}

tasks.withType(JavaCompile).configureEach { it.options.release = 17 }
tasks.withType(JavaCompile) { options.encoding = 'UTF-8' }
sourceCompatibility = targetCompatibility = JavaVersion.VERSION_17
compileJava.options.encoding = 'UTF-8'

version = '1.0.0'
archivesBaseName = 'launcher'

/* Create basic JAR */
jar {
	duplicatesStrategy 'exclude'
   	manifest {
		attributes([ "Main-Class": "com.launcher.LauncherEngine" ])
	}
}

/* Add required dependencies */
shadowJar {
   	configurations = [project.configurations.shadow]
	archiveClassifier.set('')
}

/* Main build task */
tasks.build.dependsOn shadowJar